# Generated by Django 4.2.13 on 2026-04-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('node_type', models.CharField(choices=[('group', 'Group'), ('iframe', 'Iframe'), ('panel', 'Native Panel'), ('ssh', 'SSH Terminal')], default='group', max_length=10)),
                ('url', models.URLField(blank=True, default='')),
                ('ssh_host', models.GenericIPAddressField(blank=True, null=True)),
                ('panel_type', models.CharField(blank=True, choices=[('proxmox', 'Proxmox'), ('truenas', 'TrueNAS'), ('mailcow', 'Mailcow'), ('docker', 'Docker')], default='', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_nodes', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menunode')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
